### ISSUE TITLE
Mention new cross-reference div syntax in readme

### ISSUE THREAD

**Issue by topepo** [leovan/quarto-pseudocode#3]
Thanks for the extension. 

The issue with `\numberwithin{algorithm}{chapter}` being only a LaTeX/pdf thing is solved using [Quarto’s  cross-reference div syntax](https://quarto.org/docs/authoring/cross-references-custom.html). 

You might generally recommend that folks use custom cross-referencing for the algorithm and specify the caption in Quarto (and not `\caption{}`). If you made that a hard constraint, it might significantly reduce the complexity of the extension.

**Comment by leovan** [comment]
Thanks for your advice.

I've made the extension compatible with Quarto custom cross references. It can fix the problem of cross reference in different files with `html` document for `book` type project. Except this situation, I still strongly recommend use build-in cross reference. Because Quarto custom cross reference will add an extra caption like figure, which is not a proper way to show the caption of pseudocode. More details place refer [Cross reference example](https://github.com/leovan/quarto-pseudocode/tree/main/examples/cross-reference).

**Comment by topepo** [comment]
Thanks. For a book project, I omitted `\caption{}` and used the quarto caption syntax. That worked pretty well (and enabled me to use dynamic expressions for the caption).   

Here's an example of the results: 

<img width="916" alt="image" src="https://github.com/leovan/quarto-pseudocode/assets/5731043/a6661eec-c1fc-4c2b-a84b-0cfc3baf50c8">
